<a href="https://colab.research.google.com/github/meninblack110/bakery_numpy/blob/main/bakery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
price = [2, 1, 10]
type(price)

list

In [4]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [5]:
price * quantity_sold

TypeError: ignored

In [6]:
import numpy as np

In [7]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [8]:
price_array * quantity_sold_array

array([34, 40, 10])

In [9]:
cost_array = np.array([0.25, 0.50, 5.00])

In [10]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [11]:
profit_array > 2.00

array([False, False,  True])

In [12]:
price_array = price_array + [7]
print(price_array)

[ 9  8 17]


In [13]:
price_array = price_array - [7]
# The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [14]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [15]:
print(price_array.dtype)

float64


In [16]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [17]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [18]:
quantity_sold = np.append(quantity_sold,[2, 3, 16,5])
quantity_sold


array([17, 40,  1,  2,  3, 16,  5])

In [19]:
quantity_sold[1]=39
quantity_sold

array([17, 39,  1,  2,  3, 16,  5])

In [20]:
money_sale= quantity_sold*price_array

In [21]:
money_sale

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [22]:
quantity_leftover= np.array([0,0,2,1,6,0,2])

In [23]:
discount_price= price_array/2

In [24]:
clearance_sale= quantity_leftover*discount_price
clearance_sale

array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [25]:
total= money_sale.sum()+clearance_sale.sum()
total

213.5